image:
  file: .gitpod.dockerfile
ports:
  - port: 8080
    onOpen: open-preview
tasks:
  - name: Theme
    command: >
      cd www/wp-content/themes/vuejs &&
      npm install &&
      npm run watch
  - name: MySQL
    command: >
      gp await-port 3306 &&
      mysql -e "CREATE DATABASE wordpress;" &&
      mysql -e "CREATE USER 'wordpress'@'localhost' IDENTIFIED BY 'wordpress';" &&
      mysql -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress'@'localhost';" &&
      mysql -e "SHOW DATABASES;" &&
      mysql -e "USE wordpress;"
  - name: Terminal
    command: >
      echo "";
      echo "Commands you can try:";
      echo " * apachectl stop";
      echo " * apachectl start";
      echo " * gp open /var/log/apache2/access.log";
      echo " * gp open /var/log/apache2/error.log";
  - name: Apache
    command: >
      apachectl start &&
      multitail /var/log/apache2/access.log -I /var/log/apache2/error.log
